using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PetanquePlanning.Business.Location.Domain.Entities;
using Tools.Infrastructure.EntityFramework.Abstractions;

namespace PetanquePlanning.Business.Location.Infrastructure.EntityFramework.Maps
{
    public class AdjacentDepartmentMap : EntityWithCompositeIdMap<AdjacentDepartments>
    {
        public override void Configure(EntityTypeBuilder<AdjacentDepartments> builder)
        {
            base.Configure(builder);

            //Fields
            builder
                .HasOne(x => x.FirstDepartment)
                .WithMany(x => x.AdjacentDepartments)
                .HasForeignKey(x => x.FirstDepartmentId)
                .IsRequired()
                .OnDelete(DeleteBehavior.Cascade);
            builder
                .HasOne(x => x.SecondDepartment)
                .WithMany(x => x.AdjacentDepartments)
                .HasForeignKey(x => x.SecondDepartmentId)
                .IsRequired()
                .OnDelete(DeleteBehavior.Cascade);

            builder.HasKey(x => new {x.FirstDepartmentId, x.SecondDepartmentId});

            builder.HasData(new AdjacentDepartments() {FirstDepartmentId = 39, SecondDepartmentId = 1},
                new AdjacentDepartments() {FirstDepartmentId = 40, SecondDepartmentId = 1},
                new AdjacentDepartments() {FirstDepartmentId = 70, SecondDepartmentId = 1},
                new AdjacentDepartments() {FirstDepartmentId = 72, SecondDepartmentId = 1},
                new AdjacentDepartments() {FirstDepartmentId = 74, SecondDepartmentId = 1},
                new AdjacentDepartments() {FirstDepartmentId = 75, SecondDepartmentId = 1},
                new AdjacentDepartments() {FirstDepartmentId = 8, SecondDepartmentId = 2},
                new AdjacentDepartments() {FirstDepartmentId = 52, SecondDepartmentId = 2},
                new AdjacentDepartments() {FirstDepartmentId = 60, SecondDepartmentId = 2},
                new AdjacentDepartments() {FirstDepartmentId = 61, SecondDepartmentId = 2},
                new AdjacentDepartments() {FirstDepartmentId = 78, SecondDepartmentId = 2},
                new AdjacentDepartments() {FirstDepartmentId = 81, SecondDepartmentId = 2},
                new AdjacentDepartments() {FirstDepartmentId = 18, SecondDepartmentId = 3},
                new AdjacentDepartments() {FirstDepartmentId = 22, SecondDepartmentId = 3},
                new AdjacentDepartments() {FirstDepartmentId = 43, SecondDepartmentId = 3},
                new AdjacentDepartments() {FirstDepartmentId = 59, SecondDepartmentId = 3},
                new AdjacentDepartments() {FirstDepartmentId = 64, SecondDepartmentId = 3},
                new AdjacentDepartments() {FirstDepartmentId = 72, SecondDepartmentId = 3},
                new AdjacentDepartments() {FirstDepartmentId = 5, SecondDepartmentId = 4},
                new AdjacentDepartments() {FirstDepartmentId = 6, SecondDepartmentId = 4},
                new AdjacentDepartments() {FirstDepartmentId = 13, SecondDepartmentId = 4},
                new AdjacentDepartments() {FirstDepartmentId = 25, SecondDepartmentId = 4},
                new AdjacentDepartments() {FirstDepartmentId = 84, SecondDepartmentId = 4},
                new AdjacentDepartments() {FirstDepartmentId = 85, SecondDepartmentId = 4},
                new AdjacentDepartments() {FirstDepartmentId = 25, SecondDepartmentId = 5},
                new AdjacentDepartments() {FirstDepartmentId = 39, SecondDepartmentId = 5},
                new AdjacentDepartments() {FirstDepartmentId = 74, SecondDepartmentId = 5},
                new AdjacentDepartments() {FirstDepartmentId = 84, SecondDepartmentId = 6},
                new AdjacentDepartments() {FirstDepartmentId = 25, SecondDepartmentId = 7},
                new AdjacentDepartments() {FirstDepartmentId = 31, SecondDepartmentId = 7},
                new AdjacentDepartments() {FirstDepartmentId = 39, SecondDepartmentId = 7},
                new AdjacentDepartments() {FirstDepartmentId = 44, SecondDepartmentId = 7},
                new AdjacentDepartments() {FirstDepartmentId = 49, SecondDepartmentId = 7},
                new AdjacentDepartments() {FirstDepartmentId = 70, SecondDepartmentId = 7},
                new AdjacentDepartments() {FirstDepartmentId = 85, SecondDepartmentId = 7},
                new AdjacentDepartments() {FirstDepartmentId = 52, SecondDepartmentId = 8},
                new AdjacentDepartments() {FirstDepartmentId = 56, SecondDepartmentId = 8},
                new AdjacentDepartments() {FirstDepartmentId = 60, SecondDepartmentId = 8},
                new AdjacentDepartments() {FirstDepartmentId = 11, SecondDepartmentId = 9},
                new AdjacentDepartments() {FirstDepartmentId = 32, SecondDepartmentId = 9},
                new AdjacentDepartments() {FirstDepartmentId = 67, SecondDepartmentId = 9},
                new AdjacentDepartments() {FirstDepartmentId = 20, SecondDepartmentId = 10},
                new AdjacentDepartments() {FirstDepartmentId = 52, SecondDepartmentId = 10},
                new AdjacentDepartments() {FirstDepartmentId = 53, SecondDepartmentId = 10},
                new AdjacentDepartments() {FirstDepartmentId = 78, SecondDepartmentId = 10},
                new AdjacentDepartments() {FirstDepartmentId = 90, SecondDepartmentId = 10},
                new AdjacentDepartments() {FirstDepartmentId = 32, SecondDepartmentId = 11},
                new AdjacentDepartments() {FirstDepartmentId = 35, SecondDepartmentId = 11},
                new AdjacentDepartments() {FirstDepartmentId = 82, SecondDepartmentId = 11},
                new AdjacentDepartments() {FirstDepartmentId = 15, SecondDepartmentId = 12},
                new AdjacentDepartments() {FirstDepartmentId = 31, SecondDepartmentId = 12},
                new AdjacentDepartments() {FirstDepartmentId = 35, SecondDepartmentId = 12},
                new AdjacentDepartments() {FirstDepartmentId = 47, SecondDepartmentId = 12},
                new AdjacentDepartments() {FirstDepartmentId = 49, SecondDepartmentId = 12},
                new AdjacentDepartments() {FirstDepartmentId = 82, SecondDepartmentId = 12},
                new AdjacentDepartments() {FirstDepartmentId = 83, SecondDepartmentId = 12},
                new AdjacentDepartments() {FirstDepartmentId = 31, SecondDepartmentId = 13},
                new AdjacentDepartments() {FirstDepartmentId = 84, SecondDepartmentId = 13},
                new AdjacentDepartments() {FirstDepartmentId = 85, SecondDepartmentId = 13},
                new AdjacentDepartments() {FirstDepartmentId = 26, SecondDepartmentId = 14},
                new AdjacentDepartments() {FirstDepartmentId = 51, SecondDepartmentId = 14},
                new AdjacentDepartments() {FirstDepartmentId = 62, SecondDepartmentId = 14},
                new AdjacentDepartments() {FirstDepartmentId = 19, SecondDepartmentId = 15},
                new AdjacentDepartments() {FirstDepartmentId = 44, SecondDepartmentId = 15},
                new AdjacentDepartments() {FirstDepartmentId = 47, SecondDepartmentId = 15},
                new AdjacentDepartments() {FirstDepartmentId = 49, SecondDepartmentId = 15},
                new AdjacentDepartments() {FirstDepartmentId = 64, SecondDepartmentId = 15},
                new AdjacentDepartments() {FirstDepartmentId = 17, SecondDepartmentId = 16},
                new AdjacentDepartments() {FirstDepartmentId = 23, SecondDepartmentId = 16},
                new AdjacentDepartments() {FirstDepartmentId = 80, SecondDepartmentId = 16},
                new AdjacentDepartments() {FirstDepartmentId = 87, SecondDepartmentId = 16},
                new AdjacentDepartments() {FirstDepartmentId = 88, SecondDepartmentId = 16},
                new AdjacentDepartments() {FirstDepartmentId = 34, SecondDepartmentId = 17},
                new AdjacentDepartments() {FirstDepartmentId = 80, SecondDepartmentId = 17},
                new AdjacentDepartments() {FirstDepartmentId = 86, SecondDepartmentId = 17},
                new AdjacentDepartments() {FirstDepartmentId = 22, SecondDepartmentId = 18},
                new AdjacentDepartments() {FirstDepartmentId = 37, SecondDepartmentId = 18},
                new AdjacentDepartments() {FirstDepartmentId = 42, SecondDepartmentId = 18},
                new AdjacentDepartments() {FirstDepartmentId = 46, SecondDepartmentId = 18},
                new AdjacentDepartments() {FirstDepartmentId = 59, SecondDepartmentId = 18},
                new AdjacentDepartments() {FirstDepartmentId = 90, SecondDepartmentId = 18},
                new AdjacentDepartments() {FirstDepartmentId = 22, SecondDepartmentId = 19},
                new AdjacentDepartments() {FirstDepartmentId = 23, SecondDepartmentId = 19},
                new AdjacentDepartments() {FirstDepartmentId = 47, SecondDepartmentId = 19},
                new AdjacentDepartments() {FirstDepartmentId = 64, SecondDepartmentId = 19},
                new AdjacentDepartments() {FirstDepartmentId = 88, SecondDepartmentId = 19},
                new AdjacentDepartments() {FirstDepartmentId = 40, SecondDepartmentId = 20},
                new AdjacentDepartments() {FirstDepartmentId = 53, SecondDepartmentId = 20},
                new AdjacentDepartments() {FirstDepartmentId = 59, SecondDepartmentId = 20},
                new AdjacentDepartments() {FirstDepartmentId = 71, SecondDepartmentId = 20},
                new AdjacentDepartments() {FirstDepartmentId = 72, SecondDepartmentId = 20},
                new AdjacentDepartments() {FirstDepartmentId = 90, SecondDepartmentId = 20},
                new AdjacentDepartments() {FirstDepartmentId = 28, SecondDepartmentId = 21},
                new AdjacentDepartments() {FirstDepartmentId = 36, SecondDepartmentId = 21},
                new AdjacentDepartments() {FirstDepartmentId = 57, SecondDepartmentId = 21},
                new AdjacentDepartments() {FirstDepartmentId = 37, SecondDepartmentId = 22},
                new AdjacentDepartments() {FirstDepartmentId = 64, SecondDepartmentId = 22},
                new AdjacentDepartments() {FirstDepartmentId = 88, SecondDepartmentId = 22},
                new AdjacentDepartments() {FirstDepartmentId = 17, SecondDepartmentId = 23},
                new AdjacentDepartments() {FirstDepartmentId = 34, SecondDepartmentId = 23},
                new AdjacentDepartments() {FirstDepartmentId = 47, SecondDepartmentId = 23},
                new AdjacentDepartments() {FirstDepartmentId = 48, SecondDepartmentId = 23},
                new AdjacentDepartments() {FirstDepartmentId = 88, SecondDepartmentId = 23},
                new AdjacentDepartments() {FirstDepartmentId = 40, SecondDepartmentId = 24},
                new AdjacentDepartments() {FirstDepartmentId = 71, SecondDepartmentId = 24},
                new AdjacentDepartments() {FirstDepartmentId = 91, SecondDepartmentId = 24},
                new AdjacentDepartments() {FirstDepartmentId = 39, SecondDepartmentId = 25},
                new AdjacentDepartments() {FirstDepartmentId = 70, SecondDepartmentId = 25},
                new AdjacentDepartments() {FirstDepartmentId = 85, SecondDepartmentId = 25},
                new AdjacentDepartments() {FirstDepartmentId = 27, SecondDepartmentId = 26},
                new AdjacentDepartments() {FirstDepartmentId = 61, SecondDepartmentId = 26},
                new AdjacentDepartments() {FirstDepartmentId = 62, SecondDepartmentId = 26},
                new AdjacentDepartments() {FirstDepartmentId = 77, SecondDepartmentId = 26},
                new AdjacentDepartments() {FirstDepartmentId = 79, SecondDepartmentId = 26},
                new AdjacentDepartments() {FirstDepartmentId = 96, SecondDepartmentId = 26},
                new AdjacentDepartments() {FirstDepartmentId = 42, SecondDepartmentId = 27},
                new AdjacentDepartments() {FirstDepartmentId = 46, SecondDepartmentId = 27},
                new AdjacentDepartments() {FirstDepartmentId = 62, SecondDepartmentId = 27},
                new AdjacentDepartments() {FirstDepartmentId = 73, SecondDepartmentId = 27},
                new AdjacentDepartments() {FirstDepartmentId = 79, SecondDepartmentId = 27},
                new AdjacentDepartments() {FirstDepartmentId = 92, SecondDepartmentId = 27},
                new AdjacentDepartments() {FirstDepartmentId = 57, SecondDepartmentId = 28},
                new AdjacentDepartments() {FirstDepartmentId = 25, SecondDepartmentId = 31},
                new AdjacentDepartments() {FirstDepartmentId = 35, SecondDepartmentId = 31},
                new AdjacentDepartments() {FirstDepartmentId = 49, SecondDepartmentId = 31},
                new AdjacentDepartments() {FirstDepartmentId = 85, SecondDepartmentId = 31},
                new AdjacentDepartments() {FirstDepartmentId = 33, SecondDepartmentId = 32},
                new AdjacentDepartments() {FirstDepartmentId = 66, SecondDepartmentId = 32},
                new AdjacentDepartments() {FirstDepartmentId = 82, SecondDepartmentId = 32},
                new AdjacentDepartments() {FirstDepartmentId = 83, SecondDepartmentId = 32},
                new AdjacentDepartments() {FirstDepartmentId = 41, SecondDepartmentId = 33},
                new AdjacentDepartments() {FirstDepartmentId = 48, SecondDepartmentId = 33},
                new AdjacentDepartments() {FirstDepartmentId = 65, SecondDepartmentId = 33},
                new AdjacentDepartments() {FirstDepartmentId = 66, SecondDepartmentId = 33},
                new AdjacentDepartments() {FirstDepartmentId = 83, SecondDepartmentId = 33},
                new AdjacentDepartments() {FirstDepartmentId = 41, SecondDepartmentId = 34},
                new AdjacentDepartments() {FirstDepartmentId = 48, SecondDepartmentId = 34},
                new AdjacentDepartments() {FirstDepartmentId = 82, SecondDepartmentId = 35},
                new AdjacentDepartments() {FirstDepartmentId = 45, SecondDepartmentId = 36},
                new AdjacentDepartments() {FirstDepartmentId = 50, SecondDepartmentId = 36},
                new AdjacentDepartments() {FirstDepartmentId = 51, SecondDepartmentId = 36},
                new AdjacentDepartments() {FirstDepartmentId = 54, SecondDepartmentId = 36},
                new AdjacentDepartments() {FirstDepartmentId = 57, SecondDepartmentId = 36},
                new AdjacentDepartments() {FirstDepartmentId = 38, SecondDepartmentId = 37},
                new AdjacentDepartments() {FirstDepartmentId = 42, SecondDepartmentId = 37},
                new AdjacentDepartments() {FirstDepartmentId = 87, SecondDepartmentId = 37},
                new AdjacentDepartments() {FirstDepartmentId = 88, SecondDepartmentId = 37},
                new AdjacentDepartments() {FirstDepartmentId = 42, SecondDepartmentId = 38},
                new AdjacentDepartments() {FirstDepartmentId = 50, SecondDepartmentId = 38},
                new AdjacentDepartments() {FirstDepartmentId = 73, SecondDepartmentId = 38},
                new AdjacentDepartments() {FirstDepartmentId = 87, SecondDepartmentId = 38},
                new AdjacentDepartments() {FirstDepartmentId = 70, SecondDepartmentId = 39},
                new AdjacentDepartments() {FirstDepartmentId = 74, SecondDepartmentId = 39},
                new AdjacentDepartments() {FirstDepartmentId = 71, SecondDepartmentId = 40},
                new AdjacentDepartments() {FirstDepartmentId = 72, SecondDepartmentId = 40},
                new AdjacentDepartments() {FirstDepartmentId = 48, SecondDepartmentId = 41},
                new AdjacentDepartments() {FirstDepartmentId = 65, SecondDepartmentId = 41},
                new AdjacentDepartments() {FirstDepartmentId = 46, SecondDepartmentId = 42},
                new AdjacentDepartments() {FirstDepartmentId = 73, SecondDepartmentId = 42},
                new AdjacentDepartments() {FirstDepartmentId = 44, SecondDepartmentId = 43},
                new AdjacentDepartments() {FirstDepartmentId = 64, SecondDepartmentId = 43},
                new AdjacentDepartments() {FirstDepartmentId = 70, SecondDepartmentId = 43},
                new AdjacentDepartments() {FirstDepartmentId = 72, SecondDepartmentId = 43},
                new AdjacentDepartments() {FirstDepartmentId = 49, SecondDepartmentId = 44},
                new AdjacentDepartments() {FirstDepartmentId = 64, SecondDepartmentId = 44},
                new AdjacentDepartments() {FirstDepartmentId = 70, SecondDepartmentId = 44},
                new AdjacentDepartments() {FirstDepartmentId = 50, SecondDepartmentId = 45},
                new AdjacentDepartments() {FirstDepartmentId = 54, SecondDepartmentId = 45},
                new AdjacentDepartments() {FirstDepartmentId = 57, SecondDepartmentId = 45},
                new AdjacentDepartments() {FirstDepartmentId = 86, SecondDepartmentId = 45},
                new AdjacentDepartments() {FirstDepartmentId = 59, SecondDepartmentId = 46},
                new AdjacentDepartments() {FirstDepartmentId = 78, SecondDepartmentId = 46},
                new AdjacentDepartments() {FirstDepartmentId = 90, SecondDepartmentId = 46},
                new AdjacentDepartments() {FirstDepartmentId = 92, SecondDepartmentId = 46},
                new AdjacentDepartments() {FirstDepartmentId = 48, SecondDepartmentId = 47},
                new AdjacentDepartments() {FirstDepartmentId = 83, SecondDepartmentId = 47},
                new AdjacentDepartments() {FirstDepartmentId = 83, SecondDepartmentId = 48},
                new AdjacentDepartments() {FirstDepartmentId = 54, SecondDepartmentId = 50},
                new AdjacentDepartments() {FirstDepartmentId = 73, SecondDepartmentId = 50},
                new AdjacentDepartments() {FirstDepartmentId = 80, SecondDepartmentId = 50},
                new AdjacentDepartments() {FirstDepartmentId = 86, SecondDepartmentId = 50},
                new AdjacentDepartments() {FirstDepartmentId = 87, SecondDepartmentId = 50},
                new AdjacentDepartments() {FirstDepartmentId = 54, SecondDepartmentId = 51},
                new AdjacentDepartments() {FirstDepartmentId = 62, SecondDepartmentId = 51},
                new AdjacentDepartments() {FirstDepartmentId = 53, SecondDepartmentId = 52},
                new AdjacentDepartments() {FirstDepartmentId = 56, SecondDepartmentId = 52},
                new AdjacentDepartments() {FirstDepartmentId = 78, SecondDepartmentId = 52},
                new AdjacentDepartments() {FirstDepartmentId = 56, SecondDepartmentId = 53},
                new AdjacentDepartments() {FirstDepartmentId = 71, SecondDepartmentId = 53},
                new AdjacentDepartments() {FirstDepartmentId = 89, SecondDepartmentId = 53},
                new AdjacentDepartments() {FirstDepartmentId = 62, SecondDepartmentId = 54},
                new AdjacentDepartments() {FirstDepartmentId = 73, SecondDepartmentId = 54},
                new AdjacentDepartments() {FirstDepartmentId = 56, SecondDepartmentId = 55},
                new AdjacentDepartments() {FirstDepartmentId = 58, SecondDepartmentId = 55},
                new AdjacentDepartments() {FirstDepartmentId = 68, SecondDepartmentId = 55},
                new AdjacentDepartments() {FirstDepartmentId = 89, SecondDepartmentId = 55},
                new AdjacentDepartments() {FirstDepartmentId = 89, SecondDepartmentId = 56},
                new AdjacentDepartments() {FirstDepartmentId = 68, SecondDepartmentId = 58},
                new AdjacentDepartments() {FirstDepartmentId = 89, SecondDepartmentId = 58},
                new AdjacentDepartments() {FirstDepartmentId = 72, SecondDepartmentId = 59},
                new AdjacentDepartments() {FirstDepartmentId = 90, SecondDepartmentId = 59},
                new AdjacentDepartments() {FirstDepartmentId = 63, SecondDepartmentId = 60},
                new AdjacentDepartments() {FirstDepartmentId = 81, SecondDepartmentId = 60},
                new AdjacentDepartments() {FirstDepartmentId = 77, SecondDepartmentId = 61},
                new AdjacentDepartments() {FirstDepartmentId = 78, SecondDepartmentId = 61},
                new AdjacentDepartments() {FirstDepartmentId = 81, SecondDepartmentId = 61},
                new AdjacentDepartments() {FirstDepartmentId = 96, SecondDepartmentId = 61},
                new AdjacentDepartments() {FirstDepartmentId = 73, SecondDepartmentId = 62},
                new AdjacentDepartments() {FirstDepartmentId = 2, SecondDepartmentId = 63},
                new AdjacentDepartments() {FirstDepartmentId = 81, SecondDepartmentId = 63},
                new AdjacentDepartments() {FirstDepartmentId = 66, SecondDepartmentId = 65},
                new AdjacentDepartments() {FirstDepartmentId = 11, SecondDepartmentId = 67},
                new AdjacentDepartments() {FirstDepartmentId = 69, SecondDepartmentId = 68},
                new AdjacentDepartments() {FirstDepartmentId = 89, SecondDepartmentId = 68},
                new AdjacentDepartments() {FirstDepartmentId = 71, SecondDepartmentId = 69},
                new AdjacentDepartments() {FirstDepartmentId = 89, SecondDepartmentId = 69},
                new AdjacentDepartments() {FirstDepartmentId = 91, SecondDepartmentId = 69},
                new AdjacentDepartments() {FirstDepartmentId = 72, SecondDepartmentId = 70},
                new AdjacentDepartments() {FirstDepartmentId = 89, SecondDepartmentId = 71},
                new AdjacentDepartments() {FirstDepartmentId = 91, SecondDepartmentId = 71},
                new AdjacentDepartments() {FirstDepartmentId = 75, SecondDepartmentId = 74},
                new AdjacentDepartments() {FirstDepartmentId = 93, SecondDepartmentId = 76},
                new AdjacentDepartments() {FirstDepartmentId = 94, SecondDepartmentId = 76},
                new AdjacentDepartments() {FirstDepartmentId = 95, SecondDepartmentId = 76},
                new AdjacentDepartments() {FirstDepartmentId = 81, SecondDepartmentId = 77},
                new AdjacentDepartments() {FirstDepartmentId = 90, SecondDepartmentId = 78},
                new AdjacentDepartments() {FirstDepartmentId = 92, SecondDepartmentId = 78},
                new AdjacentDepartments() {FirstDepartmentId = 96, SecondDepartmentId = 78},
                new AdjacentDepartments() {FirstDepartmentId = 92, SecondDepartmentId = 79},
                new AdjacentDepartments() {FirstDepartmentId = 93, SecondDepartmentId = 79},
                new AdjacentDepartments() {FirstDepartmentId = 96, SecondDepartmentId = 79},
                new AdjacentDepartments() {FirstDepartmentId = 86, SecondDepartmentId = 80},
                new AdjacentDepartments() {FirstDepartmentId = 87, SecondDepartmentId = 80},
                new AdjacentDepartments() {FirstDepartmentId = 83, SecondDepartmentId = 82},
                new AdjacentDepartments() {FirstDepartmentId = 85, SecondDepartmentId = 84},
                new AdjacentDepartments() {FirstDepartmentId = 88, SecondDepartmentId = 87},
                new AdjacentDepartments() {FirstDepartmentId = 91, SecondDepartmentId = 89},
                new AdjacentDepartments() {FirstDepartmentId = 93, SecondDepartmentId = 92},
                new AdjacentDepartments() {FirstDepartmentId = 95, SecondDepartmentId = 92},
                new AdjacentDepartments() {FirstDepartmentId = 94, SecondDepartmentId = 93},
                new AdjacentDepartments() {FirstDepartmentId = 96, SecondDepartmentId = 93},
                new AdjacentDepartments() {FirstDepartmentId = 95, SecondDepartmentId = 94},
                new AdjacentDepartments() {FirstDepartmentId = 96, SecondDepartmentId = 94},
                new AdjacentDepartments() {FirstDepartmentId = 78, SecondDepartmentId = 95},
                new AdjacentDepartments() {FirstDepartmentId = 93, SecondDepartmentId = 95});
        }
    }
}